version: '3' 

services:
    
  web: 
    build: ./docker-config/php
    volumes:
      - ./src/:/var/www/
    working_dir: /var/www/
    depends_on:
      - mysql

  nginx:
    image: nginx
    build: ./docker-config/nginx
    ports:
      - "81:80"
    volumes:
      - ./src/:/var/www
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  mysql:
    image: mysql:8.0
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: mainsys1
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user
      TZ: 'Asia/Tokyo'
      
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql
      - ./docker-config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    depends_on:
      - mysql-volume

  mysql-volume:
    image: busybox
    volumes:
      - ./docker-config/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8081:80
    volumes:
      - /sessions